-- Step 1: Recreate the TRANSFORMER role
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER
    COMMENT = 'Runs ML pipelines and dbt models';

GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO USER JBAUZA;  -- replace with your actual username if different

-- Step 2: Create database, schemas, and warehouse
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS PERSONAL_FINANCE
    COMMENT = 'Personal finance ML pipeline — Plaid transactions';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.RAW
    COMMENT = 'Raw Plaid API responses';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.STAGING
    COMMENT = 'Normalized transactions';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.ANALYTICS
    COMMENT = 'ML outputs: categorized transactions, subscriptions, forecasts';

CREATE WAREHOUSE IF NOT EXISTS FINANCE_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Used by personal finance pipeline';

-- Step 3: Grant TRANSFORMER access
GRANT USAGE ON DATABASE PERSONAL_FINANCE TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE FINANCE_WH TO ROLE TRANSFORMER;-- Step 1: Recreate the TRANSFORMER role
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER
    COMMENT = 'Runs ML pipelines and dbt models';

GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO USER <YOUR_SNOWFLAKE_USERNAME>;  -- replace with your actual username if different

-- Step 2: Create database, schemas, and warehouse
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS PERSONAL_FINANCE
    COMMENT = 'Personal finance ML pipeline — Plaid transactions';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.RAW
    COMMENT = 'Raw Plaid API responses';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.STAGING
    COMMENT = 'Normalized transactions';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.ANALYTICS
    COMMENT = 'ML outputs: categorized transactions, subscriptions, forecasts';

CREATE WAREHOUSE IF NOT EXISTS FINANCE_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Used by personal finance pipeline';

-- Step 3: Grant TRANSFORMER access
GRANT USAGE ON DATABASE PERSONAL_FINANCE TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE FINANCE_WH TO ROLE TRANSFORMER;

