-- Step 1: Recreate the TRANSFORMER role
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER
    COMMENT = 'Runs ML pipelines and dbt models';

GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO USER JBAUZA;  -- replace with your actual username if different

-- Step 2: Create database, schemas, and warehouse
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS PERSONAL_FINANCE
    COMMENT = 'Personal finance ML pipeline — Plaid transactions';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.RAW
    COMMENT = 'Raw Plaid API responses';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.STAGING
    COMMENT = 'Normalized transactions';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.ANALYTICS
    COMMENT = 'ML outputs: categorized transactions, subscriptions, forecasts';

CREATE WAREHOUSE IF NOT EXISTS FINANCE_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Used by personal finance pipeline';

-- Step 3: Grant TRANSFORMER access
GRANT USAGE ON DATABASE PERSONAL_FINANCE TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE FINANCE_WH TO ROLE TRANSFORMER;-- Step 1: Recreate the TRANSFORMER role
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER
    COMMENT = 'Runs ML pipelines and dbt models';

GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO USER <YOUR_SNOWFLAKE_USERNAME>;  -- replace with your actual username if different

-- Step 2: Create database, schemas, and warehouse
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS PERSONAL_FINANCE
    COMMENT = 'Personal finance ML pipeline — Plaid transactions';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.RAW
    COMMENT = 'Raw Plaid API responses';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.STAGING
    COMMENT = 'Normalized transactions';

CREATE SCHEMA IF NOT EXISTS PERSONAL_FINANCE.ANALYTICS
    COMMENT = 'ML outputs: categorized transactions, subscriptions, forecasts';

CREATE WAREHOUSE IF NOT EXISTS FINANCE_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Used by personal finance pipeline';

-- Step 3: Grant TRANSFORMER access
GRANT USAGE ON DATABASE PERSONAL_FINANCE TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.RAW TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.STAGING TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA PERSONAL_FINANCE.ANALYTICS TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE FINANCE_WH TO ROLE TRANSFORMER;

-- =============================================================================
-- Phase 1: RAW table for Plaid transactions
-- =============================================================================

USE ROLE TRANSFORMER;
USE WAREHOUSE FINANCE_WH;
USE DATABASE PERSONAL_FINANCE;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW.PLAID_TRANSACTIONS (
    -- Plaid identifiers
    TRANSACTION_ID          VARCHAR(50)  NOT NULL,
    ACCOUNT_ID              VARCHAR(50)  NOT NULL,
    ITEM_ID                 VARCHAR(50),

    -- Transaction details
    TRANSACTION_DATE        DATE         NOT NULL,
    AUTHORIZED_DATE         DATE,
    AMOUNT                  NUMBER(12,2) NOT NULL,
    ISO_CURRENCY_CODE       VARCHAR(3),
    MERCHANT_NAME           VARCHAR(500),
    NAME                    VARCHAR(500),

    -- Plaid-assigned categorization (we'll override with our ML model later)
    PERSONAL_FINANCE_CATEGORY_PRIMARY    VARCHAR(100),
    PERSONAL_FINANCE_CATEGORY_DETAILED   VARCHAR(200),
    PAYMENT_CHANNEL                      VARCHAR(50),

    -- Status flags
    PENDING                 BOOLEAN,

    -- Raw API response (full JSON for reprocessing if schema evolves)
    RAW_PAYLOAD             VARIANT,

    -- Metadata
    INGESTED_AT             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (TRANSACTION_ID)
)
COMMENT = 'Raw Plaid transactions — full API response preserved in RAW_PAYLOAD';
